name: CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-contract:
    name: "Deploy contract"
    runs-on: ubuntu-latest
    environment: Mainnet
    steps:
      - uses: actions/checkout@v2
      - run: sh "$GITHUB_WORKSPACE/.github/workflows/tools/build.sh" contract
        env:
          DEPLOY: true
          INPUT_IDENTITY: ${{ secrets.DFX_IDENTITY }}
      
  deploy-frontend:
    name: "Deploy frontend"
    runs-on: ubuntu-latest
    environment: 
      name: Mainnet
      url: "https://${{ fromJson(steps.frontend-id.outputs.id) }}.ic0.app"
    needs: deploy-contract
    steps:
      - uses: actions/checkout@v2
      - id: frontend-id
        run: |
          FRONTEND_ID="$(cat "$GITHUB_WORKSPACE/canister_ids.json" | jq -r '.frontend.ic')"
          echo "::set-output name=id::$FRONTEND_ID"
      - run: sh "$GITHUB_WORKSPACE/.github/workflows/tools/build.sh" frontend
        env:
          DEPLOY: true
          INPUT_IDENTITY: ${{ secrets.DFX_IDENTITY }}
