name: CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-contract:
    name: "Deploy contract"
    runs-on: ubuntu-latest
    environment: Mainnet
    steps:
      - uses: actions/checkout@v2
      - run: sh "$GITHUB_WORKSPACE/.github/workflows/tools/build.sh" contract
        env:
          DEPLOY: true
          INPUT_IDENTITY: ${{ secrets.DFX_IDENTITY }}
      
  deploy-frontend:
    name: "Deploy frontend"
    runs-on: ubuntu-latest
    environment: 
      name: Mainnet
      url: ${{ fromJson(steps.canister-ids.outputs.canister-ids).frontend.ic }}
    needs: deploy-contract
    steps:
      - uses: actions/checkout@v2
      - id: canister-ids
        run: |
          CANISTER_IDS="$(cat "$GITHUB_WORKSPACE/canister_ids.json")"
          echo "::set-output name=canister-ids::$CANISTER_IDS"
      - run: sh "$GITHUB_WORKSPACE/.github/workflows/tools/build.sh" frontend
        env:
          DEPLOY: true
          INPUT_IDENTITY: ${{ secrets.DFX_IDENTITY }}
